"""add view count

Revision ID: 0e69c72a4d3f
Revises: d0e3f84d90fa
Create Date: 2022-12-11 12:34:30.804097

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e69c72a4d3f"
down_revision = "d0e3f84d90fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("views", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.drop_column("views")

    # ### end Alembic commands ###
