"""rename column secret_data to data

Revision ID: 1f81ead0fd98
Revises: 7bd2692ab6dd
Create Date: 2022-11-26 12:56:24.709973

"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f81ead0fd98"
down_revision = "7bd2692ab6dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.alter_column("secret_data", new_column_name="data")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.alter_column("data", new_column_name="secret_data")

    # ### end Alembic commands ###
