"""add expires_at column

Revision ID: 2bd41d942105
Revises: fd85dbc3b740
Create Date: 2022-11-25 21:33:43.369255

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bd41d942105"
down_revision = "fd85dbc3b740"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expires_at", sa.DateTime(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.drop_column("expires_at")

    # ### end Alembic commands ###
