"""add created_at and make expires_after an Interval

Revision ID: 3492f71fb181
Revises: 1f4fe1bd5dc6
Create Date: 2022-11-25 22:17:21.233326

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3492f71fb181"
down_revision = "1f4fe1bd5dc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("expires_after", sa.Interval(), nullable=False)
        )
        batch_op.drop_column("expires_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expires_at", sa.DATETIME(), nullable=False)
        )
        batch_op.drop_column("expires_after")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
