"""rename table secrets to pastes

Revision ID: 7bd2692ab6dd
Revises: fd500896ef54
Create Date: 2022-11-26 12:34:22.725360

"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bd2692ab6dd"
down_revision = "fd500896ef54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("secrets", "pastes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("pastes", "secrets")

    # ### end Alembic commands ###
