"""rename table secrets to pastes

Revision ID: 7bd2692ab6dd
Revises: fd500896ef54
Create Date: 2022-11-26 12:34:22.725360

"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bd2692ab6dd"
down_revision = "fd500896ef54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.drop_index("ix_secrets_id")
        batch_op.create_index(batch_op.f("ix_pastes_id"), ["id"], unique=True)

    op.rename_table("secrets", "pastes")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.drop_index("ix_pastes_id")
        batch_op.create_index(batch_op.f("ix_secrets_id"), ["id"], unique=True)

    op.rename_table("pastes", "secrets")

    # ### end Alembic commands ###
