"""use expires_at to track paste expiry

Revision ID: 804e968bb0fa
Revises: d0e3f84d90fa
Create Date: 2022-12-10 18:12:55.660013

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "804e968bb0fa"
down_revision = "d0e3f84d90fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expires_at", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_temporary", sa.Boolean(), nullable=True)
        )
        batch_op.drop_column("expires_after")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("expires_after", sa.Interval(), nullable=False)
        )
        batch_op.drop_column("is_temporary")
        batch_op.drop_column("expires_at")

    # ### end Alembic commands ###
