"""add is_compressed column

Revision ID: d0e3f84d90fa
Revises: 1f81ead0fd98
Create Date: 2022-11-27 01:46:41.619711

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d0e3f84d90fa"
down_revision = "1f81ead0fd98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_compressed", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pastes", schema=None) as batch_op:
        batch_op.drop_column("is_compressed")

    # ### end Alembic commands ###
