name: CI

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ">=3.8"
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Install Pre-Commit
        run: pipx install pre-commit

      - name: Cache Pre-Commit Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Lint with Mypy and Flake8
        run: |
          poetry run pre-commit run --all mypy
          poetry run pre-commit run --all flake8

  build:
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install Dependencies
        run: poetry install

      - name: Test and Generate Coverage Report
        run: |
          poetry run pytest -n auto -d --cov=src/ --cov-branch --cov-report=lcov

      - name: Upload Coverage Report
        uses: coverallsapp/github-action@v1.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage.lcov"
          parallel: true
          flag-name: run-${{ matrix.os }}-python-${{ matrix.python-version }}

  finish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Finish Coverage Report
        uses: coverallsapp/github-action@v1.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
